export {
  getRouteTemplates,
  createRouteTemplate,
  getRouteTemplate,
  patchRouteTemplate,
  archiveRouteTemplateById,
  addRouteTemplateStop,
  patchRouteTemplateStop,
  addRouteTemplateTask,
  patchRouteTemplateTask,
  generateRoutesForDate,
  startShift,
  endShift,
  arriveAtStop,
  completeStop,
  skipStop,
  completeStopTask,
  addTaskPhoto,
} from './route-templates.service';
