/**
 * Facility type definitions — 10 standard facility types with
 * size tiers, typical area breakdowns, and key considerations.
 */
import type { FacilityType } from './types';

export const FACILITY_TYPES: FacilityType[] = [
  {
    code: 'CORPORATE_OFFICE',
    label: 'Corporate Office',
    description: 'Standard commercial office space with open areas, private offices, conference rooms, and common areas.',
    building_type_mapping: 'OFFICE',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 2000, max_sqft: 10000, midpoint_sqft: 6000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 10001, max_sqft: 50000, midpoint_sqft: 30000 },
      { code: 'LARGE', label: 'Large', min_sqft: 50001, max_sqft: 200000, midpoint_sqft: 100000 },
    ],
    typical_areas: [
      { name: 'Open Office', space_category_code: 'OFFICE_OPEN', pct: 40, floor_type_default: 'CARPET' },
      { name: 'Private Offices', space_category_code: 'OFFICE_PRIVATE', pct: 15, floor_type_default: 'CARPET' },
      { name: 'Conference Rooms', space_category_code: 'CONFERENCE_ROOM', pct: 10, floor_type_default: 'CARPET' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 8, floor_type_default: 'CERAMIC' },
      { name: 'Break Room', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 8, floor_type_default: 'VCT' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 12, floor_type_default: 'VCT' },
      { name: 'Lobby', space_category_code: 'LOBBY_RECEPTION', pct: 7, floor_type_default: 'CERAMIC' },
    ],
    key_considerations: [
      'After-hours cleaning typical (6 PM–10 PM)',
      'Day porter for high-traffic lobbies',
      'Carpet care program (spot clean weekly, extract quarterly)',
      'Conference room reset between meetings',
    ],
  },
  {
    code: 'MEDICAL_CLINIC',
    label: 'Medical Clinic',
    description: 'Outpatient medical offices, urgent care, and dental practices requiring infection-control cleaning.',
    building_type_mapping: 'MEDICAL_HEALTHCARE',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 1500, max_sqft: 5000, midpoint_sqft: 3000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 5001, max_sqft: 20000, midpoint_sqft: 12000 },
      { code: 'LARGE', label: 'Large', min_sqft: 20001, max_sqft: 60000, midpoint_sqft: 40000 },
    ],
    typical_areas: [
      { name: 'Exam Rooms', space_category_code: 'MEDICAL_EXAM', pct: 35, floor_type_default: 'VCT' },
      { name: 'Waiting Room', space_category_code: 'LOBBY_RECEPTION', pct: 15, floor_type_default: 'VCT' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 12, floor_type_default: 'CERAMIC' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 15, floor_type_default: 'VCT' },
      { name: 'Break Room', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 8, floor_type_default: 'VCT' },
      { name: 'Admin Offices', space_category_code: 'OFFICE_PRIVATE', pct: 10, floor_type_default: 'CARPET' },
      { name: 'Lobby', space_category_code: 'LOBBY_RECEPTION', pct: 5, floor_type_default: 'CERAMIC' },
    ],
    key_considerations: [
      'EPA-registered disinfectants required on all patient surfaces',
      'Bloodborne pathogen training mandatory',
      'HIPAA — no reading patient information during cleaning',
      'Sharps container monitoring (report when 3/4 full)',
    ],
  },
  {
    code: 'OUTPATIENT_SURGICAL',
    label: 'Outpatient Surgical Center',
    description: 'Ambulatory surgery centers with operating rooms, recovery areas, and sterile processing.',
    building_type_mapping: 'MEDICAL_HEALTHCARE',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 3000, max_sqft: 10000, midpoint_sqft: 6000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 10001, max_sqft: 30000, midpoint_sqft: 20000 },
      { code: 'LARGE', label: 'Large', min_sqft: 30001, max_sqft: 80000, midpoint_sqft: 50000 },
    ],
    typical_areas: [
      { name: 'Operating Rooms', space_category_code: 'MEDICAL_EXAM', pct: 25, floor_type_default: 'VCT' },
      { name: 'Pre/Post-Op', space_category_code: 'MEDICAL_EXAM', pct: 20, floor_type_default: 'VCT' },
      { name: 'Sterile Processing', space_category_code: 'MEDICAL_EXAM', pct: 10, floor_type_default: 'VCT' },
      { name: 'Waiting Room', space_category_code: 'LOBBY_RECEPTION', pct: 10, floor_type_default: 'CARPET' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 10, floor_type_default: 'CERAMIC' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 12, floor_type_default: 'VCT' },
      { name: 'Admin Offices', space_category_code: 'OFFICE_PRIVATE', pct: 8, floor_type_default: 'CARPET' },
      { name: 'Break Room', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 5, floor_type_default: 'VCT' },
    ],
    key_considerations: [
      'AORN-compliant OR turnover and terminal cleaning',
      'Between-case and end-of-day protocols documented',
      'Joint Commission survey readiness',
      'Staff must complete facility orientation before first shift',
    ],
  },
  {
    code: 'SCHOOL_K12',
    label: 'School (K-12)',
    description: 'Elementary, middle, and high schools with classrooms, gyms, cafeterias, and administrative areas.',
    building_type_mapping: 'SCHOOL_EDUCATION',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 15000, max_sqft: 50000, midpoint_sqft: 30000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 50001, max_sqft: 120000, midpoint_sqft: 80000 },
      { code: 'LARGE', label: 'Large', min_sqft: 120001, max_sqft: 300000, midpoint_sqft: 200000 },
    ],
    typical_areas: [
      { name: 'Classrooms', space_category_code: 'CLASSROOM', pct: 45, floor_type_default: 'VCT' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 15, floor_type_default: 'VCT' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 10, floor_type_default: 'CERAMIC' },
      { name: 'Cafeteria', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 10, floor_type_default: 'VCT' },
      { name: 'Gym', space_category_code: 'WAREHOUSE_PRODUCTION', pct: 8, floor_type_default: 'HARDWOOD' },
      { name: 'Admin Offices', space_category_code: 'OFFICE_PRIVATE', pct: 7, floor_type_default: 'CARPET' },
      { name: 'Lobby', space_category_code: 'LOBBY_RECEPTION', pct: 5, floor_type_default: 'CERAMIC' },
    ],
    key_considerations: [
      'Summer deep-clean window (strip/wax all VCT)',
      'Background check and fingerprinting required',
      'No cleaning while students present unless day porter',
      'Allergy-safe and green-certified products preferred',
    ],
  },
  {
    code: 'UNIVERSITY',
    label: 'University / Higher Ed',
    description: 'College campuses with lecture halls, labs, residence halls, and administrative buildings.',
    building_type_mapping: 'SCHOOL_EDUCATION',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 20000, max_sqft: 80000, midpoint_sqft: 50000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 80001, max_sqft: 200000, midpoint_sqft: 140000 },
      { code: 'LARGE', label: 'Large', min_sqft: 200001, max_sqft: 500000, midpoint_sqft: 350000 },
    ],
    typical_areas: [
      { name: 'Classrooms / Lecture Halls', space_category_code: 'CLASSROOM', pct: 35, floor_type_default: 'VCT' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 15, floor_type_default: 'VCT' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 10, floor_type_default: 'CERAMIC' },
      { name: 'Admin Offices', space_category_code: 'OFFICE_PRIVATE', pct: 12, floor_type_default: 'CARPET' },
      { name: 'Labs', space_category_code: 'MEDICAL_EXAM', pct: 10, floor_type_default: 'VCT' },
      { name: 'Common Areas', space_category_code: 'LOBBY_RECEPTION', pct: 8, floor_type_default: 'CERAMIC' },
      { name: 'Break Rooms', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 5, floor_type_default: 'VCT' },
      { name: 'Conference Rooms', space_category_code: 'CONFERENCE_ROOM', pct: 5, floor_type_default: 'CARPET' },
    ],
    key_considerations: [
      'Multiple buildings — travel time between locations',
      'Event setup/teardown for lecture halls',
      'Lab cleaning requires specialized training',
      'Semester break deep-clean schedules',
    ],
  },
  {
    code: 'INDUSTRIAL_WAREHOUSE',
    label: 'Industrial / Warehouse',
    description: 'Manufacturing plants, distribution centers, and warehouse facilities with large open production floors.',
    building_type_mapping: 'INDUSTRIAL_MANUFACTURING',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 10000, max_sqft: 50000, midpoint_sqft: 30000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 50001, max_sqft: 200000, midpoint_sqft: 120000 },
      { code: 'LARGE', label: 'Large', min_sqft: 200001, max_sqft: 500000, midpoint_sqft: 350000 },
    ],
    typical_areas: [
      { name: 'Production / Warehouse Floor', space_category_code: 'WAREHOUSE_PRODUCTION', pct: 55, floor_type_default: 'CONCRETE' },
      { name: 'Offices', space_category_code: 'OFFICE_OPEN', pct: 12, floor_type_default: 'CARPET' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 10, floor_type_default: 'CERAMIC' },
      { name: 'Break Room', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 8, floor_type_default: 'VCT' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 10, floor_type_default: 'CONCRETE' },
      { name: 'Lobby', space_category_code: 'LOBBY_RECEPTION', pct: 5, floor_type_default: 'CERAMIC' },
    ],
    key_considerations: [
      'Ride-on scrubber for large floor areas',
      'Forklift traffic — safety vests required',
      'Dust and debris control is primary concern',
      'Loading dock area cleaning often included',
    ],
  },
  {
    code: 'RETAIL_STORE',
    label: 'Retail Store',
    description: 'Retail spaces including sales floor, fitting rooms, stockroom, and customer-facing areas.',
    building_type_mapping: 'RETAIL',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 1500, max_sqft: 8000, midpoint_sqft: 4000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 8001, max_sqft: 30000, midpoint_sqft: 18000 },
      { code: 'LARGE', label: 'Large', min_sqft: 30001, max_sqft: 100000, midpoint_sqft: 60000 },
    ],
    typical_areas: [
      { name: 'Sales Floor', space_category_code: 'WAREHOUSE_PRODUCTION', pct: 60, floor_type_default: 'VCT' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 8, floor_type_default: 'CERAMIC' },
      { name: 'Stockroom', space_category_code: 'WAREHOUSE_PRODUCTION', pct: 15, floor_type_default: 'CONCRETE' },
      { name: 'Break Room', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 5, floor_type_default: 'VCT' },
      { name: 'Entrance / Vestibule', space_category_code: 'LOBBY_RECEPTION', pct: 7, floor_type_default: 'CERAMIC' },
      { name: 'Office', space_category_code: 'OFFICE_PRIVATE', pct: 5, floor_type_default: 'CARPET' },
    ],
    key_considerations: [
      'Cleaning during closed hours only (after close or before open)',
      'Glass storefront cleaning included',
      'Fitting room sanitization if applicable',
      'High-traffic entrance matting maintenance',
    ],
  },
  {
    code: 'RESTAURANT',
    label: 'Restaurant / Food Service',
    description: 'Restaurants, cafes, and food service establishments with kitchen, dining, and restroom areas.',
    building_type_mapping: 'RESTAURANT_FOOD',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 1000, max_sqft: 3000, midpoint_sqft: 2000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 3001, max_sqft: 8000, midpoint_sqft: 5000 },
      { code: 'LARGE', label: 'Large', min_sqft: 8001, max_sqft: 20000, midpoint_sqft: 12000 },
    ],
    typical_areas: [
      { name: 'Dining Area', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 45, floor_type_default: 'CERAMIC' },
      { name: 'Kitchen', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 25, floor_type_default: 'CERAMIC' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 12, floor_type_default: 'CERAMIC' },
      { name: 'Entrance', space_category_code: 'LOBBY_RECEPTION', pct: 10, floor_type_default: 'CERAMIC' },
      { name: 'Storage', space_category_code: 'WAREHOUSE_PRODUCTION', pct: 8, floor_type_default: 'CONCRETE' },
    ],
    key_considerations: [
      'Kitchen hood and exhaust not typically in scope (specialty)',
      'Grease control and floor degreasing critical',
      'Health department compliance',
      'Late-night cleaning after kitchen close',
    ],
  },
  {
    code: 'GYM_FITNESS',
    label: 'Gym / Fitness Center',
    description: 'Gyms, fitness centers, and recreational facilities with workout areas, locker rooms, and pools.',
    building_type_mapping: 'GYM_FITNESS',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 3000, max_sqft: 10000, midpoint_sqft: 6000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 10001, max_sqft: 30000, midpoint_sqft: 20000 },
      { code: 'LARGE', label: 'Large', min_sqft: 30001, max_sqft: 80000, midpoint_sqft: 50000 },
    ],
    typical_areas: [
      { name: 'Workout Floor', space_category_code: 'WAREHOUSE_PRODUCTION', pct: 45, floor_type_default: 'CONCRETE' },
      { name: 'Locker Rooms', space_category_code: 'RESTROOM', pct: 20, floor_type_default: 'CERAMIC' },
      { name: 'Reception', space_category_code: 'LOBBY_RECEPTION', pct: 10, floor_type_default: 'VCT' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 8, floor_type_default: 'CERAMIC' },
      { name: 'Office', space_category_code: 'OFFICE_PRIVATE', pct: 7, floor_type_default: 'CARPET' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 5, floor_type_default: 'VCT' },
      { name: 'Group Class Studios', space_category_code: 'CLASSROOM', pct: 5, floor_type_default: 'HARDWOOD' },
    ],
    key_considerations: [
      'Locker room and shower disinfection critical',
      'Equipment wipe-down stations (may be client responsibility)',
      'Rubber floor mats require special care',
      'Early morning or late-night cleaning windows',
    ],
  },
  {
    code: 'GOVERNMENT',
    label: 'Government Building',
    description: 'Federal, state, or municipal offices including courthouses, DMVs, and administration buildings.',
    building_type_mapping: 'GOVERNMENT',
    size_tiers: [
      { code: 'SMALL', label: 'Small', min_sqft: 5000, max_sqft: 20000, midpoint_sqft: 12000 },
      { code: 'MEDIUM', label: 'Medium', min_sqft: 20001, max_sqft: 80000, midpoint_sqft: 50000 },
      { code: 'LARGE', label: 'Large', min_sqft: 80001, max_sqft: 250000, midpoint_sqft: 150000 },
    ],
    typical_areas: [
      { name: 'Offices', space_category_code: 'OFFICE_OPEN', pct: 40, floor_type_default: 'CARPET' },
      { name: 'Restrooms', space_category_code: 'RESTROOM', pct: 10, floor_type_default: 'CERAMIC' },
      { name: 'Conference Rooms', space_category_code: 'CONFERENCE_ROOM', pct: 12, floor_type_default: 'CARPET' },
      { name: 'Hallways', space_category_code: 'HALLWAY_CORRIDOR', pct: 15, floor_type_default: 'VCT' },
      { name: 'Public Lobby', space_category_code: 'LOBBY_RECEPTION', pct: 10, floor_type_default: 'CERAMIC' },
      { name: 'Break Room', space_category_code: 'BREAK_ROOM_KITCHEN', pct: 6, floor_type_default: 'VCT' },
      { name: 'Private Offices', space_category_code: 'OFFICE_PRIVATE', pct: 7, floor_type_default: 'CARPET' },
    ],
    key_considerations: [
      'Security clearance may be required for cleaning staff',
      'Strict procurement and insurance requirements',
      'Flag and memorial care protocols',
      'Public-facing areas require day porter service',
    ],
  },
];
