/**
 * Space categories with cleanable item catalogs — 10 space types,
 * each with detailed items, materials, notes, and regulatory tags.
 */
import type { SpaceCategory } from './types';

export const SPACE_CATEGORIES: SpaceCategory[] = [
  {
    code: 'OFFICE_OPEN',
    label: 'Open Office',
    description: 'Open-plan office areas with workstations, shared desks, and common equipment.',
    cleanable_items: [
      { name: 'Workstation Surfaces', typical_materials: ['Laminate', 'Wood veneer', 'Glass'], notes: 'Wipe desktops, monitor stands, keyboard trays.', regulatory_tags: ['ISSA'] },
      { name: 'Desk Chairs', typical_materials: ['Fabric', 'Mesh', 'Leather'], notes: 'Spot-clean spills; deep-clean fabric quarterly.', regulatory_tags: [] },
      { name: 'Wastebaskets', typical_materials: ['Plastic', 'Metal'], notes: 'Empty and reline daily. Sanitize weekly.', regulatory_tags: [] },
      { name: 'Carpet / Floor', typical_materials: ['Carpet tile', 'Broadloom', 'LVT'], notes: 'Vacuum daily, spot-treat stains, extract quarterly.', regulatory_tags: ['ISSA'] },
      { name: 'Shared Printers / Copiers', typical_materials: ['Plastic', 'Glass'], notes: 'Wipe exterior surfaces and touch screens.', regulatory_tags: [] },
      { name: 'Light Switches & Outlets', typical_materials: ['Plastic'], notes: 'High-touch disinfection daily.', regulatory_tags: ['CDC'] },
      { name: 'Partition Panels', typical_materials: ['Fabric', 'Glass', 'Laminate'], notes: 'Dust weekly, spot-clean as needed.', regulatory_tags: [] },
    ],
  },
  {
    code: 'OFFICE_PRIVATE',
    label: 'Private Office',
    description: 'Enclosed individual offices with door, desk, and personal storage.',
    cleanable_items: [
      { name: 'Desk & Credenza', typical_materials: ['Wood', 'Laminate', 'Glass top'], notes: 'Dust and polish. Do not disturb papers.', regulatory_tags: [] },
      { name: 'Guest Chairs', typical_materials: ['Fabric', 'Leather'], notes: 'Vacuum or wipe weekly.', regulatory_tags: [] },
      { name: 'Bookshelf / Shelving', typical_materials: ['Wood', 'Metal'], notes: 'Dust shelves and visible book tops monthly.', regulatory_tags: [] },
      { name: 'Floor', typical_materials: ['Carpet', 'Hardwood'], notes: 'Vacuum or dust-mop daily.', regulatory_tags: [] },
      { name: 'Wastebasket & Recycling', typical_materials: ['Plastic', 'Metal'], notes: 'Empty daily.', regulatory_tags: [] },
      { name: 'Door Handle & Light Switch', typical_materials: ['Metal', 'Plastic'], notes: 'Disinfect high-touch points daily.', regulatory_tags: ['CDC'] },
      { name: 'Window Sill (interior)', typical_materials: ['Wood', 'Vinyl', 'Stone'], notes: 'Dust weekly.', regulatory_tags: [] },
    ],
  },
  {
    code: 'RESTROOM',
    label: 'Restroom',
    description: 'Public and private restroom facilities with toilets, sinks, and dispensers.',
    cleanable_items: [
      { name: 'Toilets / Urinals', typical_materials: ['Porcelain', 'Stainless steel'], notes: 'Bowl-clean inside, wipe exterior and base. Check flush valve.', regulatory_tags: ['CDC', 'OSHA'] },
      { name: 'Sinks & Countertops', typical_materials: ['Porcelain', 'Solid surface', 'Stainless'], notes: 'Clean basin, faucet handles, and surrounding counter.', regulatory_tags: ['CDC'] },
      { name: 'Mirrors', typical_materials: ['Glass'], notes: 'Streak-free clean with glass cleaner.', regulatory_tags: [] },
      { name: 'Dispensers (soap, towel, TP)', typical_materials: ['Plastic', 'Stainless steel'], notes: 'Refill and wipe exterior. Report low stock.', regulatory_tags: [] },
      { name: 'Floors', typical_materials: ['Ceramic tile', 'Epoxy', 'Terrazzo'], notes: 'Mop with disinfectant. Scrub grout lines weekly.', regulatory_tags: ['CDC'] },
      { name: 'Partition Walls & Doors', typical_materials: ['Laminate', 'Stainless steel'], notes: 'Wipe all surfaces including door locks and handles.', regulatory_tags: ['CDC'] },
      { name: 'Trash Receptacles', typical_materials: ['Stainless steel', 'Plastic'], notes: 'Empty, reline, and sanitize exterior.', regulatory_tags: [] },
      { name: 'Air Freshener / Vent', typical_materials: ['Plastic', 'Metal grate'], notes: 'Replace refills, dust vent covers.', regulatory_tags: [] },
    ],
  },
  {
    code: 'LOBBY_RECEPTION',
    label: 'Lobby / Reception',
    description: 'Building entrance, reception desk area, and visitor waiting zones.',
    cleanable_items: [
      { name: 'Reception Desk', typical_materials: ['Stone', 'Laminate', 'Glass'], notes: 'Dust and polish top surface. Wipe phone and keyboard.', regulatory_tags: [] },
      { name: 'Seating (waiting area)', typical_materials: ['Fabric', 'Leather', 'Vinyl'], notes: 'Vacuum or wipe. Check under cushions weekly.', regulatory_tags: [] },
      { name: 'Entry Glass / Doors', typical_materials: ['Glass', 'Aluminum frame'], notes: 'Clean both sides. High fingerprint area.', regulatory_tags: [] },
      { name: 'Floor', typical_materials: ['Stone', 'Ceramic', 'Terrazzo', 'Carpet'], notes: 'High-traffic — may need day porter attention. Mat maintenance.', regulatory_tags: ['ISSA'] },
      { name: 'Elevator Doors & Call Buttons', typical_materials: ['Stainless steel', 'Plastic'], notes: 'Polish doors, disinfect buttons.', regulatory_tags: ['CDC'] },
      { name: 'Directory / Signage', typical_materials: ['Acrylic', 'Glass', 'Metal'], notes: 'Dust and clean fingerprints.', regulatory_tags: [] },
      { name: 'Plants / Planters', typical_materials: ['Ceramic', 'Metal'], notes: 'Remove debris from soil. Wipe planter exterior.', regulatory_tags: [] },
    ],
  },
  {
    code: 'HALLWAY_CORRIDOR',
    label: 'Hallway / Corridor',
    description: 'Connecting corridors, stairwells, and transition spaces between areas.',
    cleanable_items: [
      { name: 'Floor', typical_materials: ['VCT', 'Carpet', 'Concrete', 'Terrazzo'], notes: 'Primary cleaning item. Auto-scrub or dust-mop depending on surface.', regulatory_tags: ['ISSA'] },
      { name: 'Baseboards', typical_materials: ['Vinyl', 'Wood', 'Rubber'], notes: 'Wipe or damp-mop. Scuff marks from carts and equipment.', regulatory_tags: [] },
      { name: 'Light Switches & Plates', typical_materials: ['Plastic'], notes: 'Disinfect daily.', regulatory_tags: ['CDC'] },
      { name: 'Fire Extinguisher Cabinet', typical_materials: ['Metal', 'Glass'], notes: 'Dust top and wipe glass face monthly.', regulatory_tags: [] },
      { name: 'Handrails (stairwells)', typical_materials: ['Metal', 'Wood'], notes: 'Disinfect daily in high-traffic buildings.', regulatory_tags: ['CDC'] },
      { name: 'Water Fountains / Bottle Fillers', typical_materials: ['Stainless steel'], notes: 'Sanitize basin and button. Polish exterior.', regulatory_tags: ['CDC'] },
    ],
  },
  {
    code: 'BREAK_ROOM_KITCHEN',
    label: 'Break Room / Kitchen',
    description: 'Employee break areas, kitchenettes, and cafeteria spaces.',
    cleanable_items: [
      { name: 'Countertops', typical_materials: ['Laminate', 'Granite', 'Solid surface'], notes: 'Sanitize entire surface. Remove food debris.', regulatory_tags: ['CDC'] },
      { name: 'Sink & Faucet', typical_materials: ['Stainless steel'], notes: 'Clean basin, polish faucet, wipe backsplash.', regulatory_tags: [] },
      { name: 'Microwave (exterior)', typical_materials: ['Plastic', 'Stainless steel'], notes: 'Wipe exterior and handle. Interior per client agreement.', regulatory_tags: [] },
      { name: 'Refrigerator (exterior)', typical_materials: ['Stainless steel', 'Plastic'], notes: 'Wipe door and handle. Interior typically client responsibility.', regulatory_tags: [] },
      { name: 'Tables & Chairs', typical_materials: ['Laminate', 'Plastic', 'Metal'], notes: 'Sanitize table tops and chair arms daily.', regulatory_tags: ['CDC'] },
      { name: 'Vending Machines', typical_materials: ['Metal', 'Glass front'], notes: 'Wipe exterior and selection buttons.', regulatory_tags: [] },
      { name: 'Floor', typical_materials: ['VCT', 'Ceramic'], notes: 'Damp-mop with degreaser. Sticky spots common.', regulatory_tags: [] },
      { name: 'Trash & Recycling', typical_materials: ['Plastic', 'Stainless steel'], notes: 'Empty, reline, and sanitize exterior.', regulatory_tags: [] },
    ],
  },
  {
    code: 'CONFERENCE_ROOM',
    label: 'Conference Room',
    description: 'Meeting rooms with tables, AV equipment, and whiteboards.',
    cleanable_items: [
      { name: 'Conference Table', typical_materials: ['Wood', 'Laminate', 'Glass'], notes: 'Dust and polish. Remove water rings and food residue.', regulatory_tags: [] },
      { name: 'Chairs', typical_materials: ['Mesh', 'Leather', 'Fabric'], notes: 'Vacuum or wipe. Check for spills under arm rests.', regulatory_tags: [] },
      { name: 'Whiteboard / Glass Board', typical_materials: ['Porcelain enamel', 'Glass'], notes: 'Clean only if marked "OK to erase" or per client instruction.', regulatory_tags: [] },
      { name: 'AV Equipment / Screen', typical_materials: ['Plastic', 'Glass'], notes: 'Dust only — do not use wet cleaners on screens.', regulatory_tags: [] },
      { name: 'Phone / Speakerphone', typical_materials: ['Plastic'], notes: 'Disinfect handset and buttons.', regulatory_tags: ['CDC'] },
      { name: 'Floor', typical_materials: ['Carpet', 'Hardwood'], notes: 'Vacuum or dust-mop daily.', regulatory_tags: [] },
      { name: 'Wastebasket', typical_materials: ['Plastic', 'Metal'], notes: 'Empty and reline.', regulatory_tags: [] },
    ],
  },
  {
    code: 'WAREHOUSE_PRODUCTION',
    label: 'Warehouse / Production',
    description: 'Large open floor areas for manufacturing, storage, distribution, or retail sales floor.',
    cleanable_items: [
      { name: 'Production Floor', typical_materials: ['Sealed concrete', 'Epoxy', 'Polished concrete'], notes: 'Ride-on scrubber for large areas. Walk-behind for aisles.', regulatory_tags: ['OSHA'] },
      { name: 'Loading Dock', typical_materials: ['Concrete', 'Metal'], notes: 'Sweep debris, pressure wash monthly if in scope.', regulatory_tags: [] },
      { name: 'Racking / Shelving (lower 8 ft)', typical_materials: ['Metal'], notes: 'Dust accessible surfaces. Report spills or hazards.', regulatory_tags: ['OSHA'] },
      { name: 'Safety Stations', typical_materials: ['Metal', 'Plastic'], notes: 'Clean eyewash stations, first aid cabinets, fire equipment.', regulatory_tags: ['OSHA'] },
      { name: 'Tool Cribs / Workbenches', typical_materials: ['Metal', 'Wood'], notes: 'Wipe surfaces if empty. Do not move tools or parts.', regulatory_tags: [] },
      { name: 'Overhead Doors / Rails', typical_materials: ['Metal'], notes: 'Dust tracks and lower door panels monthly.', regulatory_tags: [] },
    ],
  },
  {
    code: 'CLASSROOM',
    label: 'Classroom',
    description: 'Teaching spaces with desks, whiteboards, and student storage areas.',
    cleanable_items: [
      { name: 'Student Desks / Tables', typical_materials: ['Laminate', 'Plastic', 'Wood'], notes: 'Sanitize all surfaces daily. Check under desks for gum.', regulatory_tags: ['CDC'] },
      { name: 'Student Chairs', typical_materials: ['Plastic', 'Metal frame'], notes: 'Wipe seats and backs.', regulatory_tags: [] },
      { name: 'Teacher Desk', typical_materials: ['Laminate', 'Wood'], notes: 'Dust surface only — do not move papers or materials.', regulatory_tags: [] },
      { name: 'Whiteboard / Chalkboard', typical_materials: ['Porcelain', 'Slate'], notes: 'Clean only if instructed. Erase and clean tray.', regulatory_tags: [] },
      { name: 'Floor', typical_materials: ['VCT', 'Carpet tile'], notes: 'Dust-mop or vacuum daily. Strip and wax VCT during breaks.', regulatory_tags: ['ISSA'] },
      { name: 'Cubbies / Storage', typical_materials: ['Wood', 'Laminate'], notes: 'Wipe exterior monthly. Interior typically teacher responsibility.', regulatory_tags: [] },
      { name: 'Door Handle & Light Switch', typical_materials: ['Metal', 'Plastic'], notes: 'Disinfect daily.', regulatory_tags: ['CDC'] },
      { name: 'Wastebasket', typical_materials: ['Plastic'], notes: 'Empty daily.', regulatory_tags: [] },
    ],
  },
  {
    code: 'MEDICAL_EXAM',
    label: 'Medical / Exam Room',
    description: 'Clinical exam rooms, treatment rooms, and procedural spaces requiring infection-control cleaning.',
    cleanable_items: [
      { name: 'Exam Table', typical_materials: ['Vinyl upholstery', 'Metal frame'], notes: 'Disinfect between patients if doing turnover cleaning.', regulatory_tags: ['CDC', 'OSHA'] },
      { name: 'Countertops & Cabinets', typical_materials: ['Laminate', 'Solid surface'], notes: 'Sanitize all horizontal surfaces. Clean cabinet pulls.', regulatory_tags: ['CDC'] },
      { name: 'Sink', typical_materials: ['Stainless steel', 'Porcelain'], notes: 'Scrub basin and fixtures. Check soap dispenser.', regulatory_tags: ['CDC'] },
      { name: 'Medical Equipment (exterior)', typical_materials: ['Plastic', 'Metal'], notes: 'Wipe exterior only. Do not adjust settings or unplug.', regulatory_tags: ['CDC', 'JOINT_COMMISSION'] },
      { name: 'Floor', typical_materials: ['VCT', 'Sheet vinyl'], notes: 'Damp-mop with EPA-registered disinfectant.', regulatory_tags: ['CDC', 'EPA'] },
      { name: 'Light Switch & Door Handle', typical_materials: ['Plastic', 'Metal'], notes: 'High-touch — disinfect every cleaning cycle.', regulatory_tags: ['CDC'] },
      { name: 'Sharps Container (monitor only)', typical_materials: ['Plastic'], notes: 'DO NOT handle. Report when 3/4 full.', regulatory_tags: ['OSHA'] },
      { name: 'Biohazard Waste (monitor only)', typical_materials: ['Plastic bag/bin'], notes: 'DO NOT handle contents. Report when full for pickup.', regulatory_tags: ['OSHA'] },
      { name: 'Wall-mounted Dispensers', typical_materials: ['Plastic', 'Metal'], notes: 'Refill hand sanitizer, glove boxes. Wipe exterior.', regulatory_tags: ['CDC'] },
    ],
  },
];
